sudo: required
language: generic

services:
    - docker
    
before_install:
    - docker build -t vsoloviev/Docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vsoloviev/Docker-react npm run test -- --coverage
    
