sudo: required
language: generic

services:
    - docker
    
before_install:
    - docker build -t vsoloviev/docker-react -f Dockerfile.dev .

script:
    - docker run vsoloviev/docker-react npm run test -- --coverage
    
